### PR TITLE
readme enhancements

### PR DESCRIPTION
**Pull request by akshayitzme**

### CODE REVIEW

**Comment by akshayitzme** [comment]
Branch delete cheyyade 😂

**Comment by MQ-xz** [comment]
🙄?

**Comment by akshayitzme** [comment]
readme-enhancements ee branch .. delete aakan pattule 🤔

**Comment by MQ-xz** [comment]
y ?

**Comment by akshayitzme** [comment]
No worries njn delete aki 😅✌️

**Comment by MQ-xz** [comment]
ha vokey yendhayirn scn ?

**Comment by akshayitzme** [comment]
illa... readme edt njn seperate branch il aan cheyde (readme-enhance).. ath master lek merge cheydapo no need for that branch athan delete aakan paranje 😄

**Pull request merged**
